<?php
/**
 * Block editor rules.
 *
 * The editor shows only the blocks in the allow list below. Everything else
 * is hidden. To change the list, use the 'sgwrd_allowed_blocks' filter in a
 * child theme. Do not edit this file.
 *
 * @package ACF_Starter
 */

defined( 'ABSPATH' ) || exit;

/**
 * Get the core blocks that editors may use.
 *
 * @return string[]
 */
function sgwrd_allowed_core_blocks() {

	return array(
		// Text.
		'core/paragraph',
		'core/heading',
		'core/list',
		'core/list-item',
		'core/quote',
		'core/separator',
		'core/table',

		// Layout.
		'core/group',
		'core/columns',
		'core/column',
		'core/buttons',
		'core/button',
		'core/spacer',

		/*
		 * Keep this block. WordPress uses it to show content that was made with
		 * a block that is no longer there. Without it, that content is lost.
		 */
		'core/missing',
	);
}

/**
 * Get the ACF blocks that this theme registers.
 *
 * @return string[]
 */
function sgwrd_registered_acf_blocks() {

	$blocks = array();

	foreach ( WP_Block_Type_Registry::get_instance()->get_all_registered() as $name => $block ) {
		if ( str_starts_with( $name, 'acf/' ) ) {
			$blocks[] = $name;
		}
	}

	return $blocks;
}

/**
 * Limit the editor to the allowed blocks.
 *
 * @param bool|string[]           $allowed Current value. True means every block.
 * @param WP_Block_Editor_Context $context The editor context.
 * @return bool|string[]
 */
function sgwrd_allowed_block_types( $allowed, $context ) {

	$post = $context->post ?? null;

	/*
	 * WooCommerce builds the cart, the checkout and the order pages from its own
	 * blocks. Those blocks have many inner blocks, and the list changes with each
	 * WooCommerce release. On those pages the theme allows every block, so the
	 * shop keeps working after an update.
	 */
	if ( $post instanceof WP_Post && sgwrd_is_woocommerce_page( $post->ID ) ) {
		return true;
	}

	$blocks = array_merge( sgwrd_allowed_core_blocks(), sgwrd_registered_acf_blocks() );

	/**
	 * Filter the list of allowed blocks.
	 *
	 * @param string[]                $blocks  Block names.
	 * @param WP_Block_Editor_Context $context The editor context.
	 */
	$blocks = apply_filters( 'sgwrd_allowed_blocks', $blocks, $context );

	return array_values( array_unique( $blocks ) );
}
add_filter( 'allowed_block_types_all', 'sgwrd_allowed_block_types', 10, 2 );

/**
 * Check if a post is one of the WooCommerce system pages.
 *
 * @param int $post_id Post ID.
 * @return bool
 */
function sgwrd_is_woocommerce_page( $post_id ) {

	if ( ! sgwrd_has_woocommerce() ) {
		return false;
	}

	$pages = array_filter(
		array(
			wc_get_page_id( 'cart' ),
			wc_get_page_id( 'checkout' ),
			wc_get_page_id( 'myaccount' ),
			wc_get_page_id( 'shop' ),
			wc_get_page_id( 'terms' ),
		)
	);

	return in_array( (int) $post_id, array_map( 'intval', $pages ), true );
}

/**
 * Turn off the core block patterns and the pattern directory.
 *
 * Patterns bring styling that this theme does not want. Register your own
 * patterns in a child theme when you need them.
 */
function sgwrd_disable_patterns() {

	remove_theme_support( 'core-block-patterns' );
}
add_action( 'after_setup_theme', 'sgwrd_disable_patterns', 20 );
add_filter( 'should_load_remote_block_patterns', '__return_false' );

/**
 * Turn off the openverse media search in the editor.
 *
 * @param array $settings Editor settings.
 * @return array
 */
function sgwrd_disable_openverse( $settings ) {

	$settings['enableOpenverseMediaCategory'] = false;

	return $settings;
}
add_filter( 'block_editor_settings_all', 'sgwrd_disable_openverse' );

/**
 * Add a block category for the theme blocks.
 *
 * @param array $categories Block categories.
 * @return array
 */
function sgwrd_block_category( $categories ) {

	array_unshift(
		$categories,
		array(
			'slug'  => 'sgwrd-blocks',
			'title' => __( 'Theme blocks', 'acf-starter' ),
			'icon'  => null,
		)
	);

	return $categories;
}
add_filter( 'block_categories_all', 'sgwrd_block_category' );

/**
 * Register the block style variations.
 *
 * A style variation is how you give an editor a design choice without giving
 * them a colour picker. Add the CSS for each one in assets/css/style.css.
 */
function sgwrd_register_block_styles() {

	register_block_style(
		'core/group',
		array(
			'name'  => 'surface',
			'label' => __( 'Surface', 'acf-starter' ),
		)
	);

	register_block_style(
		'core/group',
		array(
			'name'  => 'bordered',
			'label' => __( 'Bordered', 'acf-starter' ),
		)
	);

	register_block_style(
		'core/button',
		array(
			'name'  => 'outline-dark',
			'label' => __( 'Outline', 'acf-starter' ),
		)
	);

	register_block_style(
		'core/heading',
		array(
			'name'  => 'eyebrow',
			'label' => __( 'Eyebrow', 'acf-starter' ),
		)
	);

	register_block_style(
		'core/list',
		array(
			'name'  => 'plain',
			'label' => __( 'No markers', 'acf-starter' ),
		)
	);
}
add_action( 'init', 'sgwrd_register_block_styles' );

/**
 * Keep the classic widget screen. The block widget screen adds settings that
 * this theme does not need.
 */
add_filter( 'use_widgets_block_editor', '__return_false' );
